### ISSUE TITLE
mark a release

### ISSUE THREAD

**Issue by dericed** [vi/mkvparse#5]
I find this utility really useful and would like to make a homebrew installer for it. Could you mark a release so that I could point the installer to that, otherwise the installer can only be head-only.

**Comment by vi** [comment]
Are you interested mostly in xml2mkv or in mkvparse as a library?

**Comment by dericed** [comment]
xml2mkv and mkv2xml

**Comment by vi** [comment]
Please mark the issue as closed when you verify that Homebrew works well for the tools.

**Comment by dericed** [comment]
Tried, but got

```
Sorry, this project does not meet our notability criteria:

GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
```

**Comment by vi** [comment]
Does Homebrew support attachable additional PPA-like repositories?

**Comment by retokromer** [comment]
@vi Could you possibly make a release with the tag `v1.1.0`? Thank you! (The las release is still `v1.0.0`.)

**Comment by vi** [comment]
@retokromer , Done: https://github.com/vi/mkvparse/releases/tag/v1.1.0

**Comment by retokromer** [comment]
Thank you very much! I will update the brew formula tomorrow (it’s already late here).

**Comment by retokromer** [comment]
@vi Thank you! On my end, the [formula](https://github.com/amiaopensource/homebrew-amiaos/blob/master/mkvparse.rb) works now fine with both v1.1.0 and HEAD.

@dericed I guess this issue can be closed.

**Comment by dericed** [comment]
works for me
