### ISSUE TITLE
Cannot import mkvparse as a "library"

### ISSUE THREAD

**Issue by JohnLM** [vi/mkvparse#6]
Cannot import `mkvparse` on Python 2.7 as it is installed by `setup.py`

**Steps to reproduce:**
1. Install the package via `setup.py`
2. Try `import mkvparse` in interpreter (running from anywhere _but_ the working directory of mkvparse).

**Possible solutions:**
**A.** Add an empty `__init__.py` file in the tree.
This will make `mkvparse` a proper package, allowing importing modules as:
`from mkvparse import mkvparse`

**B.** Declare `mkvparse` as "bare" module
This will avoid installing `mkvparse.py` under a subdirectory, so that module is visible directly and can be imported as:
`import mkvparse`

Here's the changes:
```
diff --git a/setup.py b/setup.py
index 442d480..1b3aab0 100644
--- a/setup.py
+++ b/setup.py
@@ -20,2 +20 @@ setup(
-    packages=['mkvparse'],
-       package_dir={'mkvparse': ''},
+    py_modules=['mkvparse'],
```

The diff will install _only_ `mkvparse.py`. You may add `mkvgen` and `mkvuser` to `py_modules`, but they do not appear to be reusable modules but rather executable scripts.
More about including scripts in package [here](https://pythonhosted.org/setuptools/setuptools.html#automatic-script-creation)

**Comment by vi** [comment]
Currently mkvgen is a template to be copyied and pasted into your program.

Do you feel it should be available as a proper API, like mkvparse, but in reverse?

Note that mkvgen's matroska files are simplified and are not designed to be stored permanently, they should be fed into FFmpeg or mkvmerge to make proper matroska files.

**Comment by JohnLM** [comment]
Hmm, it would be neat to have `mkvgen` turned into usable module with a proper API. I don't see this happening without significant refactoring. It's also a question whether it's useful and interesting to you and/or community.

Personally, I'm interested only in the `mkvparse` functionality. I'm using it to process video frames from an .mkv in Python, but I need not the process to be reversible (i.e., I'm not putting results back into .mkv).

**Comment by JohnLM** [comment]
In addition, `mkvuser`, `xml2mkv` and `mkv2xml` could be installed as _scripts_ or turned into [_executable modules_](https://docs.python.org/2/tutorial/modules.html#executing-modules-as-scripts) , the latter of which just requires wrapping executed statements with
`if __name__ == "__main__":`

**Comment by vi** [comment]
I never tried actually installing mkvparse into the system, usually just copied it into projects.

What do you suggest short term (before mkvgen turned into API) and long-term? I expect `xml2mkv` (which has duplicated parts with mkvgen) and `mkv2xml` be useful for somebody, so they maybe should not be excluded from installation...

Can you prepare a pull request which makes mkvparse more install-friendly?

**Comment by JohnLM** [comment]
Sure! The changes are on #7 
For the time being, `mkvgen.py` will be ignored by the setuptools. It can be added once it's mature enough.

**Comment by JohnLM** [comment]
With #7 merged, this issue is solved.
